### ISSUE TITLE
Area calculation of a triangle

### ISSUE THREAD

**Issue by mayisa87** [pascal-o/CostCalculator#4]
https://github.com/pascal-o/CostCalculator/blob/023ccc0b914cf7b891e5a90be6f1d284201b9aec/CostCalculator/Program.cs#L44-L51

You could use the usual default calculation for an triangle area:

![image](https://github.com/pascal-o/CostCalculator/assets/130921606/31659b54-5a75-4485-a629-a8caec4b6353)

So base length * height /2

**Comment by pascal-o** [comment]
I could easily use the default calculation for a triangle but I thought to myself that in real life, it would so difficult for an everyday person perfectly measure the height of the triangular room (which must be at a right angle - 90 degrees - to the "base"). Measuring the 3 sides makes the room area calculation more practical and accurate. What do you think?

**Comment by incredibleLeitman** [comment]
In fact which formula you are actually using is not that important :D

The idea of this issue just was to show that you can modify specific given parts in your code without breaking something. This becomes very important later on when projects are getting a lot bigger or when working with other people.

Usually we encourage our clients to try out a few things to get familiar with their code,
but in most cases we dont dictate how exactly your program should look like :D
